### ISSUE TITLE
Looking for help adding Chess War Features to this program.

### ISSUE THREAD

**Issue by zotz** [esbudylin/HexChess#1]
I have begin trying to modify World.gd to add a simple chess war level 1 feature to this program.

I am not understanding something and am looking for help, hints, to be pointed in the right direction.

If you drop this version or World.gd into the program and run you may see what I am trying to do and where I am going wrong:

https://github.com/zotz/bitsandpieces/blob/main/Hexagonal_Chess_World.gd

There are some comments at the top of that file that provide links that might help you grasp what I mean by chess war.

I need to jump in at the point where a piece is taken, fight a battle, and then leave the winner on the board and remove the loser. In regular chess, the attacker is always the "winner", in chess war, the defender sometimes wins.

**Comment by esbudylin** [comment]
Hi! Just

**Comment by esbudylin** [comment]
Hi! Here's a quickfix I managed to come up with for your player_turn function. It seems like your problem was you were killing a war result winner instead of a loser piece. In my fix I just worked around it, but you may want to fix your cwl1 function :). Note, that I replaced your global zattackwon variable with a local one just for convenience sake. Btw, I've recently done some refactoring on this project, I recommend you to switch to a newer version. If you have any further questions, feel free to ask.

```
func player_turn(clicked_cell, sync_mult = false):
	var zattackwon
	
	if sync_mult:
		active_piece = get_node(active_piece_path)
		
	if clicked_cell in $TileMap.chessmen_coords:
		for piece in $TileMap.chessmen_list:
			if piece.tile_position == clicked_cell and piece !=active_piece:
				# try fighting chl1 for now
				warresult = cwl1(active_piece, piece)
				print("War result winner: ", warresult)
				$TileMap.kill_piece(warresult)
				print("Just killed a piece - dR.")
				zattackwon = active_piece == warresult
				break
				
	elif 'Pawn' in active_piece.name and clicked_cell in $TileMap.jumped_over_tiles\
	and clicked_cell in $TileMap.pawn_attack(active_piece, active_piece.tile_position, false):
		$TileMap.kill_piece($TileMap.jumped_over_tiles[clicked_cell])
		
		if get_tree().is_network_server():
			var dead_npc_path = str($TileMap.jumped_over_tiles[clicked_cell].get_path())
			rpc("sync_kill_piece", dead_npc_path)

	print("zattackwon is: ", zattackwon)
	if not zattackwon:
		print("Trying to erase: ", active_piece, " at: ", active_piece.tile_position)
		$TileMap.chessmen_coords.erase(active_piece.tile_position)
		active_piece.position = $TileMap.map_to_world(clicked_cell)
		active_piece.tile_position = clicked_cell
		$TileMap.chessmen_coords[clicked_cell] = active_piece
	else:
		print("What should we do if defence won?")
		
	$TileMap.draw_map()
	
	for tile in $TileMap.passable_tiles:
		if $TileMap.passable_tiles[tile] == active_piece:
			$TileMap.jumped_over_tiles[tile] = active_piece

	$TileMap.passable_tiles = {}
```

**Comment by zotz** [comment]
Thanks for the prompt response.

However, unless I am missing something, I think your code always erases the wrong piece.

I have made a short screen capture and uploaded it here:

https://github.com/zotz/bitsandpieces/blob/main/hexchesswar_001.mp4

Am I being a bit dense? I am tired today.

Question: In the original code, on which line is the piece taken? (Is it the same line for all pieces? (Am I calling the war function in the correct spot?) Does calling a war function when a piece is to be taken make sense with the way you have this coded?

drew

**Comment by esbudylin** [comment]
I just thought the erasing of a loser piece was a desirable outcome of a failed attack :) If you don't want to do anything in case of a failed attack, try something like this. Answering your question, a piece is taken from a board by the $TileMap.kill_piece function. Currently your code covers all cases of attacks except en passant taking (a check for en passant is also located in the player_turn function: a block beginning with `elif 'Pawn' in active_piece.name`). Your approach to this code seems totally reasonable to me.

```
			if piece.tile_position == clicked_cell and piece !=active_piece:
				# try fighting chl1 for now
				warresult = cwl1(active_piece, piece)
				print("War result winner: ", warresult)
				print("Just killed a piece - dR.")
				zattackwon = active_piece == warresult
				if zattackwon:			
					$TileMap.kill_piece(piece)
				break
```

**Comment by zotz** [comment]
I may have something working now that takes the losing piece off of the board:

https://github.com/zotz/bitsandpieces/blob/main/Hexagonal_Chess_World.gd

next I would like to add a text box to the right side of the game board where I
can report the battle info which is now getting printed to the console.

I am further thinking of adding a toggle to the options box to allow for playing in war mode L1 or War Mode Lx or no war mode...

You mentioned newer code. I think I got the version I have from within Godot 3.5.1 What is the best way to get the newer code?

**Comment by esbudylin** [comment]
> You mentioned newer code. I think I got the version I have from within Godot 3.5.1 What is the best way to get the newer code?

I recommend you to fork this repository, this way you'll be able to see future updates on this project and merge them with your code if needed.

**Comment by zotz** [comment]
I have made decent progress.

I am looking for further help. Would you be willing to have an interactive chat? Video, voice, or text can work for me.

I have uploaded a complete .tgz file that can play regular hex chess, L1 Hex Chess War, and have begun adding L2 Hes Chess War. I am interesting on chatting about how to best go about that.

It is here: https://github.com/zotz/bitsandpieces/blob/main/HexChessModded_L2_001.tgz

all the best,

drew

**Comment by zotz** [comment]
Level 2 may be fully workable now:

https://github.com/zotz/bitsandpieces/blob/main/HexChessModded_L2_003.tgz

Please take a look and give feedback.

I am going to try and change my naming conventions to match yours. (Mine are currently just random.)

**Comment by esbudylin** [comment]
Hi! I quite like the direction of your project. I noticed a few bugs, if you set up a proper git repository, I can send you a pull request. I don't like live chats, so if you have any questions about my code, either ask them here or we can contact via email.

**Comment by zotz** [comment]
My problem with git is I have never used it enough to get comfortable / good with it and I use it so sporadically that I forget what I do know between uses.

I do intend to set one up for this if I make enough progress that it looks like I will continue development into the future and on to higher levels. For the moment, I think I might get there as I am happy with the progress so far.

Many thanks for your fine foundation that I am able to build on. I have made more progress in the few days since I have found your code than I have in many years of on and off efforts...

you can email me at zlocz@yahoo.com and I will send you my daily email.

**Comment by zotz** [comment]
> I recommend you to fork this repository, this way you'll be able to see future updates on this project and merge them with your code if needed.


> ff you set up a proper git repository


I have decided to try and take the plunge with this. Can you advise on the proper steps to get there? (I am on linux if that makes a difference.)
