### ISSUE TITLE
Help with logic differences in new player_turn function.

### ISSUE THREAD

**Issue by zotz** [esbudylin/HexChess#2]
I have begun working in the forked code. I think I am making decent progress.

Currently trying to get L1 battles working.

It would be very helpful if you could briefly outline the logic flow / thought process in the new code.

This is a snippet:

`	print("In Game.gd in func player_turn")
	if sync_mult:
		active_piece = get_node(game_type_node.active_piece_path)
		
	if clicked_cell in $TileMap.chessmen_coords:
		if game_debug: print("Active piece is: ", active_piece)
		# Tle player tunr logic seems very different.
		# perhaps I kick off the fight about here
		dpiece = $TileMap.chessmen_coords[clicked_cell]
		if war_level == "Level0":
			if game_debug: print("\n\n-----In War Level: ", war_level)
			warresult = dpiece
		elif war_level == "Level1":
			if game_debug: print("\n\n-----In War Level: ", war_level)
			warresult = cwl1(active_piece, dpiece)
		elif war_level == "Level2":
			if game_debug: print("\n\n-----In War Level: ", war_level)
			warresult = cwl2(active_piece, dpiece)
		else:
			warresult = dpiece

		#$TileMap.kill_piece($TileMap.chessmen_coords[clicked_cell])
		
		$TileMap.kill_piece(warresult)`

Then I think this is messing me up:

`	$TileMap.move_piece(active_piece, clicked_cell)
	$TileMap.draw_map()
	$TileMap.update_jumped_over_tiles(active_piece)`

I am moving the active_piece to the new cell after it has lost the battle and been "$TileMap.kill"ed.

Hints would be greatly appreciated.

Once I get Level1 going, I will move on to level 2.

**Comment by esbudylin** [comment]
Hi! In your previous code you solved this problem in this fashion:

```
print("zattackwon is: ", zattackwon)
	if zattackwon:
		print("Trying to erase: ", active_piece, " at: ", active_piece.tile_position)
		$TileMap.chessmen_coords.erase(active_piece.tile_position)			
		active_piece.position = $TileMap.map_to_world(clicked_cell)
		active_piece.tile_position = clicked_cell
		$TileMap.chessmen_coords[clicked_cell] = active_piece
		zattackwon = true
	else:
		print("What should we do if defence won?")
		# at the end, set zattackwon to true
		zattackwon = true
```

I think this decision will work as well on a newer code. Just note that the code below is now separated into the $TileMap.move_piece function. 

```
		$TileMap.chessmen_coords.erase(active_piece.tile_position)			
		active_piece.position = $TileMap.map_to_world(clicked_cell)
		active_piece.tile_position = clicked_cell
		$TileMap.chessmen_coords[clicked_cell] = active_piece
```

Also, there wasn't much change on the player_turn logic. Besides some code was separated into a new functions (move_piece, update_jumped_over_tiles), the only difference is that now we find a piece on a clicked cell by lookup in the dictionary instead of iterating over all chessmen.
