### ISSUE TITLE
Flip board when playing remotely as black

### ISSUE THREAD

**Issue by zotz** [esbudylin/HexChess#4]
I think it would be a good idea to put black on the bottom when playing remotely as black.

Do you see this as something you might work on?

drew

**Comment by zotz** [comment]
You may find some clues on how someone else does it here:

[https://chessboardjs.com/examples#2001](url)

**Comment by esbudylin** [comment]
The porposal was implemented with [this](https://github.com/esbudylin/HexChess/commit/51d1bdd0405df6f1e65de655942b862a43869b74) commit.

**Comment by zotz** [comment]
Fantastic. I will have to try it out and see how it looks.
