### ISSUE TITLE
Promotion Hexes

### ISSUE THREAD

**Issue by DerBananenBieger** [esbudylin/HexChess#6]
In the Glinski variant it is possible for the rightmost (and leftmost) pawn to promote in their first move by taking towards right (and left) and reaching the opponents promotion hex.

**Comment by esbudylin** [comment]
Hi! Thank you for the report. I'll be sure to fix it next time I revisit this code.

**Comment by esbudylin** [comment]
Bug was fixed with 2.0 release.
